config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#index'
  get 'sessions/new'
  post '/sessions' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'
  get 'signout' => 'sessions#destroy'

  get 'static_pages/index'

  resources :posts, only: %i[index new create]
  
  resources :users, only: %i[index new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, :text, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :email_down_case
  before_create :remember_me

  has_many :posts

  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
  REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: REGEX_EMAIL }
  validates :password, presence: true, length: { in: 6..50 }
  has_secure_password

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  private

  def email_down_case
    email.downcase!
  end

  def remember_me
    self.remember_token = User.new_token
    self.remember_digest = User.digest(remember_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def logged_in_user
    redirect_to root_url unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      remember user
      redirect_to posts_path
    else
      flash[:errors] = ["Invalid Combination"]
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    user = current_user
    sign_out(user)
    forget(user)
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            remember @user
            redirect_to posts_path
        else
            flash[:errors] = @user.errors.full_messages
            render 'new'
        end
    end

    private

        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    user = if session[:user_id]
             User.find(sessions[:user_id])
           elsif cookies[:user_id]
             User.find(cookies[:user_id])
           end
  end

  def logged_in?
    !!current_user
  end

  def current_user=(user)
    sessions[:user_id] = user.id
    current_user = current_user
  end

  def remember(user)
    user.remember
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_digest] = user.remember_digest
  end

  def forget(_user)
    cookies.delete(:user_id)
    cookies.delete(:remember_digest)
  end

  def log_in(user)
    current_user = user
  end

  def sign_out(user)
    session.delete(:user_id) if user == current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<h1>Exclusive</h1>
<% if logged_in? %>
    <%= link_to  "Log Out", signout_path %><br>
    <%= link_to  "Create a Post", new_post_path %>
<% else %>
    <%= link_to  "Log in", sessions_new_path %><br>
    <%= link_to  "Sign Up", new_user_path %>
<% end %>
<br><%= link_to "Show Posts", posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% @posts.each do |post| %>
    <% if logged_in? %>
        Author: <%= post.user.name %><br>
    <% else %>
        <h4>**Log in to see the author**</h4><br>
    <% end %>
    Title: <%= post.title %><br>
    Post:<br><%= post.text %><br>
    <br><br>
<% end %>

app/views/posts/new.html.erb
<h1>Create a Post!</h1>
<%= form_for @post do |f| %>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %><br>
    <%= f.text_area :text, placeholder: "Put your text here..." %><br>
    <%= f.submit "Create Post" %>
<% end %>

app/views/static_pages/index.html.erb
<h1>Welcome To this Exclusive Social Media</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
    <%= f.label :name, "Name" %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email, "E-mail" %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation, "Repeat Password" %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit %><br>
<% end %>

<% if flash[:errors] %>
  <div>       
    <% flash[:errors].each do |e| %>
      <p><%= e %></p>
    <% end %> 
  </div>
<% end %>